### ISSUE TITLE
Design merge issue in login and sign up page

### ISSUE THREAD

**Issue by VanshGolakiya-2910** [StudybuddiesMentor/Studybuddies_Infosys_Internship_Oct2024#11]
![Screenshot 2024-11-15 223927](https://github.com/user-attachments/assets/40a9d815-9554-40a6-a219-775e1282f792)
![Screenshot 2024-11-15 223845](https://github.com/user-attachments/assets/42716f69-38eb-47ca-bf20-101f946af3e4)
![Screenshot 2024-11-15 223603](https://github.com/user-attachments/assets/62c84247-1474-4fab-998f-719f564b671e)
![Screenshot 2024-11-15 223533](https://github.com/user-attachments/assets/a80650c0-c78c-46fe-90dc-5787c62e7aa2)

**Comment by jatin-sh01** [comment]
![screenshot-1731827947816](https://github.com/user-attachments/assets/7bafd6fc-f7ef-4dbe-94cc-1af859326559)
![screenshot-1731827919563](https://github.com/user-attachments/assets/6ef2a0d8-b2fc-40c4-9826-138362fe153f)
![screenshot-1731827870090](https://github.com/user-attachments/assets/8cb47880-2884-45f6-a786-9910d97e4e99)
updated Design merge issue in login and sign up page
