### ISSUE TITLE
Logo Click Not Redirecting to Homepage

### ISSUE THREAD

**Issue by aryank354** [StudybuddiesMentor/Studybuddies_Infosys_Internship_Oct2024#3]
Expected Behavior
When clicking on the logo in the navigation bar, the user should be redirected to the homepage in the register and login page

Current Behavior
Clicking on the logo does not navigate to the homepage. Instead, it either has no action or fails to redirect as expected.

![WhatsApp Image 2024-10-30 at 2 54 53 PM](https://github.com/user-attachments/assets/05d39d4d-5e29-4e86-b15b-992f5bbbd4f3)

**Comment by Namitamunjal** [comment]
Done for the after login part
